<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c6e79198-c0d9-48ea-a6f2-fcd4e166e481</testSuiteGuid>
   <testCaseLink>
      <guid>acb26983-0613-4bde-b1ca-3bf21a39db6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>c58bb38f-6fc0-44bc-b79f-47df7dd531cf</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Demo/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a6adce5a-0ae7-488e-a774-a73ca4eac97d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a6adce5a-0ae7-488e-a774-a73ca4eac97d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c58bb38f-6fc0-44bc-b79f-47df7dd531cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a6adce5a-0ae7-488e-a774-a73ca4eac97d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>73a5294c-2bb3-4ce5-8b20-519f644e4412</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
