<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BrowsingContextInspector</name>
   <tag></tag>
   <elementGuidId>f2556c10-326a-4249-81c8-ae635d6c20e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'BrowsingContextInspector')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a[title=&quot;class in org.openqa.selenium.bidi&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4374c02f-36bd-4143-8305-c9283b72812b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>BrowsingContextInspector.html</value>
      <webElementGuid>ad855281-f877-4b96-aaba-0e95badf15c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.bidi</value>
      <webElementGuid>9d606bdd-c6e3-4e56-801c-5d2d4583b478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>5ad8612a-d397-4363-bb9a-34771378c814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BrowsingContextInspector</value>
      <webElementGuid>82351a44-998c-4c44-8c2b-878f13e79e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[2]/ul[1]/li[4]/a[1]</value>
      <webElementGuid>0733b37c-ee59-4a62-8851-de22be81b27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>3d8804c4-d00d-4898-bdd4-b04623ce825f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BrowsingContextInspector')]</value>
      <webElementGuid>d271ca8f-ae6f-403c-a04c-b8bacb0bbe48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiDiSessionStatus'])[1]/following::a[1]</value>
      <webElementGuid>35ce671c-a419-4d47-a577-803ce4e2adeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiDiProvider'])[1]/following::a[2]</value>
      <webElementGuid>ced16c6c-2a39-4c46-8e0b-c646d40de560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Command'])[1]/preceding::a[1]</value>
      <webElementGuid>db7d942a-44a8-48ff-b0d1-95a269ef3c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connection'])[1]/preceding::a[2]</value>
      <webElementGuid>db885a8b-2b88-4c80-8e2c-314804d74de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BrowsingContextInspector']/parent::*</value>
      <webElementGuid>7bd72009-6cb5-44d8-88ac-1662eb942922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'BrowsingContextInspector.html')]</value>
      <webElementGuid>91a5e1df-2a5f-41d1-9058-f4ecd5bd0e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>c2d17abf-23a7-41f2-bce8-7ed958b1313d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'BrowsingContextInspector.html' and @title = 'class in org.openqa.selenium.bidi' and (text() = 'BrowsingContextInspector' or . = 'BrowsingContextInspector')]</value>
      <webElementGuid>a08bf7cf-89d1-46dd-a2b3-408594c3f3c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
